USE TSQL;
GO

ALTER TABLE Sales.Customers
ADD 
    startdate DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL DEFAULT SYSUTCDATETIME()
,   enddate DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL DEFAULT ('9999-12-31 23:59:59.9999999')
,   PERIOD FOR SYSTEM_TIME (startdate,enddate);

ALTER TABLE Sales.Customers
	SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = Sales.CustomersHistory));
GO